name: splitemate
description: "Splitemate"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  jwt_decoder: ^2.0.1
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2
  gradient_borders: ^1.0.0
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  provider: ^6.1.2
  otp_pin_field: ^1.2.9+1
  google_sign_in: ^6.2.1
  sqflite: ^2.4.1
  path: ^1.8.0
  web_socket_channel: ^3.0.1
  intl: ^0.20.1
  connectivity_plus: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: GT-Walsheim-Pro
      fonts:
        - asset: assets/fonts/GTWalsheimProRegular.ttf
        - asset: assets/fonts/GTWalsheimProBold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Bold.ttf
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 600
